name: FinancialVueDo
services:
  - build_command: yarn build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: blairun/FinancialVueBeDo
    name: FinancialVueDo
